### PR TITLE
Fix compatibility with metro apps and UWP

### LINKED ISSUE #13: Windows 8.1 下使用小狼毫 TSF 导致 Store Application 宿主崩溃
1. 将系统惟一输入法设置成小狼毫 TSF
2. 打开「邮件」「应用商店」等应用
3. 查看事件查看器，选择 Windows 事件，可以发现来自 Apps 源的崩溃记录

### LINKED ISSUE #57: Windows 10 系统下 Cortana 没法很好地兼容
在cortana里两种输入方式都没办法输入，会崩溃，请问有解决办法吗

### PR DESCRIPTION
**Pull request by nameoverflow**
1. Rewrite inter-process communication to work with metro apps and UWP (closes #13 and closes #57)

2. Fix illegal memory access in inline preedit mode

3. Improve high DPI performance and be compatible with old Windows version (https://github.com/rime/weasel/issues/28)

### CODE REVIEW

**Comment by Prcuvu** [comment]
I'd suggest separating commit fb751ce into another Pull Request.

**Comment by nameoverflow** [comment]
之前调试时我修改了部分 build config 导致在 CI 中无法正常 build 64 位的文件，并且不小心一并提交了。fb751ce 这个 commit 是为了修复这个错误。

需要把它删除吗？或者合并到之前的 commit ？

**Comment by Prcuvu** [comment]
@nameoverflow 不用。最后合并时我会采用 squash 的方式。

**Comment by nameoverflow** [comment]
Now I think everything of this patch is done

**Comment by nameoverflow** [comment]
Well, I'll also try to fit this code base to XP SDK.

However is it truly necessary to keep a developing master line compatible with such a OS version? Isnt a legacy code base or compatible release be enough?

**Comment by Prcuvu** [comment]
`regsvr32` fails to register TSF DLL, reporting "LoadLibrary failed (weasel.dll)- Invalid access to memory location". This only occurs on Windows XP.

**Comment by nameoverflow** [comment]
Whether this means a `LoadLibrary` call in the DLL failed or host process load the DLL failed?

**Comment by nameoverflow** [comment]
Seems something goes wrong in `dllmain`...

**Comment by nameoverflow** [comment]
I picked 6 files `Globals.h`, `dllmain.cpp`, `stdafx.h`, `Globals.cpp`, `WeaselCommon.h`, `targetver.h` from `master` and compiled them with `boost::filesystem` into a single DLL, try to run `regsvr32` in XP SP3 and it also failed.

According to [this SO thread](https://stackoverflow.com/questions/7693596/c-loadlibrary-error-noaccess-invalid-access-to-memory-location) this issue can be caused by a incorrect global variables initialization, however i think all globals there have appropriate initialized.

**Comment by Prcuvu** [comment]
It could be a VS runtime fault.

In fact, the problem has been observed since I switched build toolset from VS 2013 to VS 2015. I even tried to compile code from commits before the switch (working when compiled with VS 2013) with VS 2015, the problem still occurred.

There are two ways to tackle the problem: switching back to VS 2013, or a painstaking debugging. Both ways are very demotivating.

**Comment by nameoverflow** [comment]
It's a boost fault, not VS

I make a simple test program calling `LoadLibrary` to load the dll above, debug in windbg, it gives

```
ModLoad: 00700000 0071e000   C:\test\Dll1.dll
(5b8.254): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
eax=00000000 ebx=00000008 ecx=00000000 edx=00150608 esi=0070f12c edi=00000001
eip=00701f2e esp=0012f784 ebp=0012f794 iopl=0         nv up ei ng nz na po nc
cs=001b  ss=0023  ds=0023  es=0023  fs=003b  gs=0000             efl=00010282
Dll1!boost::system::generic_category+0x2e:
00701f2e 8b0c88          mov     ecx,dword ptr [eax+ecx*4] ds:0023:00000000=????????
```

the exception raised from `boost::system`.

after comment the line `#include <boost/filesystem.hpp>` in `stdafx.h`, the dll loaded fine.

**Comment by nameoverflow** [comment]
The `LoadLibrary` issue is caused by boost, `boost/filesystem.hpp` makes a failed system call in dll initialization and throws a exception. After removing `boost::filesystem` from `stdafx.h` (since `winrt` branch do not dependent it any more), `regsvr32` works fine.

However I found the input methods (TSF and IME) still don't work.

**Comment by nameoverflow** [comment]
I tried to use windbg in XP but found nothing meaningful. An access violation to a weird address occurred immediately after `weasel.dll` loaded.

```
ModLoad: 10000000 10045000   C:\WINDOWS\system32\weasel.dll
ModLoad: 00be0000 00be3000   C:\WINDOWS\system32\api-ms-win-core-synch-l1-2-0.dll
(510.6ac): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
eax=000c2a08 ebx=00000000 ecx=000c2a08 edx=000a0608 esi=000c3bd0 edi=00000000
eip=dc005120 esp=0007eba4 ebp=0007ebc4 iopl=0         nv up ei pl nz na po nc
cs=001b  ss=0023  ds=0023  es=0023  fs=003b  gs=0000             efl=00010202
dc005120 ??              ???
0:000> g


 *** An Access Violation occurred in C:\WINDOWS\system32\notepad.exe:

The instruction at DC005120 tried to read from an invalid address, DC005120

 *** enter .exr 0007E8BC for the exception record
 ***  enter .cxr 0007E8D8 for the context
 *** then kb to get the faulting stack

(510.6ac): Break instruction exception - code 80000003 (first chance)
eax=00000000 ebx=00020658 ecx=7c987870 edx=0007e52f esi=00000000 edi=0007e7c8
eip=7c92120e esp=0007e748 ebp=0007e784 iopl=0         nv up ei pl zr na pe nc
cs=001b  ss=0023  ds=0023  es=0023  fs=003b  gs=0000             efl=00000246
ntdll!DbgBreakPoint:
7c92120e cc              int     3
0:000> .exr 0007E8BC
ExceptionAddress: dc005120
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 00000000
   Parameter[1]: dc005120
Attempt to read from address dc005120
0:000> .cxr 0007E8D8
eax=000c2a08 ebx=00000000 ecx=000c2a08 edx=000a0608 esi=000c3bd0 edi=00000000
eip=dc005120 esp=0007eba4 ebp=0007ebc4 iopl=0         nv up ei pl nz na po nc
cs=001b  ss=0023  ds=0023  es=0023  fs=003b  gs=0000             efl=00010202
dc005120 ??              ???
0:000> kb
  *** Stack trace for last set context - .thread/.cxr resets it
ChildEBP RetAddr  Args to Child              
WARNING: Frame IP not in any known module. Following frames may be wrong.
0007eba0 10004891 05700e35 0007ec20 000c2a08 0xdc005120
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\WINDOWS\system32\ole32.dll - 
0007ebe4 769c13e4 000c2448 00000000 0007f5b0 weasel!WeaselTSF::WeaselTSF+0x1 [c:\users\hcyue\code\weasel\weaseltsf\weaseltsf.cpp @ 79]
0007ec6c 769c10b3 76ab7150 00000000 0007f228 ole32!CoMarshalInterface+0x2973
0007ecac 769c1302 0007f228 00000000 0007f774 ole32!CoMarshalInterface+0x2642
```

**Comment by lotem** [comment]
If we cannot(*) satisfy both versions of systems, we might want to create a branch for the XP-compatible version and release a separate build for XP.

Does the current master work for XP before this change?

**Comment by lotem** [comment]
@Prcuvu My personal preference when merging a pull-request is to create a merge commit i.e. `git merge --no-ff`. 
I think keeping all commits in the pull-request would help readers to break down the big change and understand the code better. I would only squash and merge if the commits are not helpful in this way.

**Comment by Prcuvu** [comment]
It has long been broken on Windows XP since I changed the default build toolset to VS 2015, see #77. Therefore it cannot be solved by simply creating a separate branch.

Indeed, merge-commit is more appropriate in this case since there are actually several distinct changes in the PR. I will turn to this way eventually.

**Comment by mrhso** [comment]
刚才水群里有人反馈 WeaselServer.exe /quit 失效了。

**Comment by lotem** [comment]
If we've figured out that the breakage on XP isn't introduced by this change, then it shouldn't block merging this pull request. Though, we can choose to hold it until the XP issue is resolved on master, if it doesn't take a long time. In that case, please fix XP-compatible build separately from this branch.

**Comment by Prcuvu** [comment]
All right, I'll merge this PR once the assumption mentioned in #77 gets confirmed.

**Comment by lotem** [comment]
`WeaselServer.exe /quit` 的問題需要驗證。
他的作用是安裝升級的時候結束算法服務進程，以完成對 `*.exe`、`*.dll` 的覆蓋。

如果有其他辦法從外部結束進程也可以。
否則不僅要保證新版本能正常退出，爲了升級安裝還需要兼容舊版本算法服務的退出方式。

**Comment by nameoverflow** [comment]
@lotem 这个问题已经在 https://github.com/rime/weasel/pull/106/commits/523c7efd044a177a2626abd0df5eaac7410bc40d 修复

**Comment by zhaozg** [comment]
When time to merge?  thanks @nameoverflow excited work.

**Comment by nameoverflow** [comment]
@zhaozg 哪种 not working？用的哪一版？

**Comment by zhaozg** [comment]
@nameoverflow  我從 https://ci.appveyor.com/api/buildjobs/xljaj06ytrsryd1i/artifacts/output%2Farchives%2Fweasel-0.9.30.0-installer.exe 下載，是你的Patch的最後版本的 appveyor 自動生產的安裝包

**Comment by nameoverflow** [comment]
@zhaozg 哦，这个分支的build是不能用的，因为librime版本问题。你可以前往 https://ci.appveyor.com/project/nameoverflow/weasel/build/buildfix%20build%2010/artifacts 获取可用版本。

**Comment by zhaozg** [comment]
Thnaks to @nameoverflow

**Comment by nameoverflow** [comment]
@zhaozg 崩溃？什么样的崩溃？现在已经合并到 master 了，主分支的 build 也可以用，有问题可以直接发 issue

**Comment by david50407** [comment]
When will Weasel release new version including this change?

**Comment by zhaozg** [comment]
@nameoverflow  Prcuvu  fixed the problem in master HEAD, and thank you again.

**Pull request merged**
