### PR TITLE
build: drop build hant

### PR DESCRIPTION
**Pull request by fxliang**
hant build has been dropped by WeaselTSF, WEASEL_HANT only affects resource info of WeaselIME, so drop it with multi-translation in WeaselIME.rc, and don't build hant in build.bat

### CODE REVIEW

**Review by lotem — APPROVED** [review]
帮忙看看 readme 还还是 install md 有没有写 build 命令

**Review by determ1ne — APPROVED** [review]
vc++ 项目里的 Hant build 也可以一起删掉

**Comment by fxliang** [comment]
> vc++ 项目里的 Hant build 也可以一起删掉

ReleaseHant和ReleaseHans都清掉了

**Comment by fxliang** [comment]
> 帮忙看看 readme 还还是 install md 有没有写 build 命令

没有build hant，不过正式发版前应该要更新一下INSTALL.md

**Pull request merged**
