### PR TITLE
Apply clang format

### PR DESCRIPTION
**Pull request by Bambooin**
Apply clang format and add lint job.

The runner of clang format lint job is macOS due to outdated clang format(14) in latest ubuntu-latest runner.

For the conflicts in pending pull requests, you can try with this command:
```
# checkout your pr branch
git fetch
git reset upstream/master
make clang-format-apply
git commit
git push -f
```

**Please don't use squash in this pull request, this will break blame ignore file.**

CI is passed in: https://github.com/Bambooin/weasel/actions

### CODE REVIEW

**Comment by fxliang** [comment]
for windows developing, some suggestions:

- about actions: a lint job **need**ed by actual action job, `runs-on: windows-2022` with LLVM intalled,  `shell: bash`
- about clang-format: write a simple bat/ps1 to install clang-format for developers, sample like 
```bat
@echo off

if "%PROCESSOR_ARCHITECTURE%"=="AMD64" (
    rem 64 bit system
    rem powershell -Command "(New-Object Net.WebClient).DownloadFile('https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.6/LLVM-17.0.6-win64.exe', 'LLVM-17.0.6-win64.exe')"
    rem LLVM-17.0.6-win64.exe /S
    rem or maybe
    rem output/7z.exe e LLVM-17.0.6-win64.exe bin/clang-format.exe -o.
    rem rm LLVM-17.0.6-win64.exe
) else (
    rem 32 bit system
    rem powershell -Command "(New-Object Net.WebClient).DownloadFile('https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.6/LLVM-17.0.6-win32.exe', 'LLVM-17.0.6-win32.exe')"
    rem LLVM-17.0.6-win32.exe /S
    rem or maybe
    rem output/7z.exe e LLVM-17.0.6-win32.exe bin/clang-format.exe -o.
    rem rm LLVM-17.0.6-win32.exe
)
pause
```
- about makefile : write a shell script for git bash instead of makefile, for local and ci

**Comment by Bambooin** [comment]
All code review were settled down, and the CI is passed: https://github.com/Bambooin/weasel/actions

**Comment by Bambooin** [comment]
Done, waiting for your signal to apply clang format.

**Comment by lotem** [comment]
All conflict-free PRs are merged.
Please go ahead with the code style change.

**Review by lotem — APPROVED** [review]

**Comment by Bambooin** [comment]
Done, the CI is pass in: https://github.com/Bambooin/weasel/actions

**Comment by fxliang** [comment]
I try to fetch your code, and run ./clang-format.sh -i locally,  got
```
Please lint your code by "./clang-format.sh -n".
```

**Comment by fxliang** [comment]
> @fxliang What's your clang-format version, we need clang-format 17?
> 
> Can you share your log from the format script?
> 
> The CI is running on Windows, and I use macOS platform, both platforms were passing.

well, my problem... clang-format comes with vs2022 so old.

**Pull request merged**
