### PR TITLE
feat(tsf): accomplish candidate UI interfaces

### LINKED ISSUE #127: 输入焦点切出时不会丢弃当前 composition
来自 QQ 群的用户反馈：

image

image

### PR DESCRIPTION
**Pull request by nameoverflow**
Workaround for #110.
Fixes #127.

- [x] migrate UI to TSF

- [x] implement interface for UI-less mode

- [x] sync style and configure between frontend and backend

### CODE REVIEW

**Comment by nameoverflow** [comment]
So how to clear CI boost cache?
CI failed since these changes require a new boost library...

**Comment by nameoverflow** [comment]
@lotem 
Is there a way to detect RIME config changes? I wanna do some synchronizing between front-end and server only when necessary...

**Comment by lotem** [comment]
@nameoverflow Configuration only changes at each deployment. Maybe we can load settings to the frontend only once for a continuous Rime session.

**Comment by nameoverflow** [comment]
Looks fine now.
May need more test.

**Pull request merged**
